### ISSUE TITLE
Open to contribute :) 

### ISSUE THREAD

**Issue by rejamen** [awisky/odoo-sqs#1]
Hi, this is more like a question rather than an issue.
I would like to contribute here, migrating the addon to v17.

I forked the repo and once is ready I want to open a PR here. But I see this addon depends on 'mountrix' therefore I can not install it and test it. 

I can try to migrate the code blindly, but I would like to test it locally first.

Any way to get this 'mountrix' addon?

Regards

**Comment by awisky** [comment]
@rejamen I removed the unnecessary dependency. Please try it. You are welcome to contribute Bro!
